# Generated by Django 5.2.6 on 2026-04-22 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0002_initial'),
        ('distributors', '0003_alter_distributor_address_distributoronboarding'),
        ('fleet', '0003_vehicle_capacity_m3'),
        ('orders', '0005_order_delivery_window_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('DISPATCHED', 'Despachado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20)),
                ('provider', models.CharField(default='ors', max_length=40)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_distance_km', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_duration_min', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_load_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_load_m3', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('unassigned_summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='distributors.distributor')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_route_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dispatch_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('DISPATCHED', 'Despachada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='CONFIRMED', max_length=20)),
                ('total_stops', models.PositiveIntegerField(default=0)),
                ('total_distance_km', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_duration_min', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('load_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('load_m3', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_runs', to='fleet.driverprofile')),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='routing.routeplan')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_runs', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ARRIVED', 'Arribada'), ('DELIVERED', 'Entregada'), ('SKIPPED', 'Omitida')], default='PENDING', max_length=20)),
                ('planned_eta', models.DateTimeField()),
                ('window_start_at', models.DateTimeField()),
                ('window_end_at', models.DateTimeField()),
                ('leg_distance_km', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('leg_duration_min', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('demand_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('demand_m3', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stops', to='deliveries.delivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='orders.order')),
                ('route_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routing.routerun')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='routeplan',
            index=models.Index(fields=['distributor', 'dispatch_date'], name='routing_rou_distrib_b0574b_idx'),
        ),
        migrations.AddIndex(
            model_name='routeplan',
            index=models.Index(fields=['distributor', 'status'], name='routing_rou_distrib_c3b5d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routerun',
            unique_together={('route_plan', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route_run', 'order'), ('route_run', 'sequence')},
        ),
    ]
