# Generated by Django 5.2.6 on 2026-04-30 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0004_distributor_address_notes_distributor_postal_code'),
        ('orders', '0005_order_delivery_window_end_and_more'),
        ('products', '0004_product_characteristics_product_discount_name_and_more'),
        ('routing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=180, unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En proceso'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteOptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(default='multi_driver_best_insertion_v1', max_length=80)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStopLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('uom', models.CharField(blank=True, max_length=40)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('volume_m3', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('delivered_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('returned_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('difference_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('capacity_estimated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='routeplan',
            name='capacity_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='planning_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='preview_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_route_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='route_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='routing_status',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='routerun',
            name='origin_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routerun',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='address_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routestop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='routeplan',
            index=models.Index(fields=['distributor', 'dispatch_date', 'status'], name='routing_rou_distrib_9bb2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='routeplan',
            index=models.Index(fields=['status', 'dispatch_date'], name='routing_rou_status_347350_idx'),
        ),
        migrations.AddField(
            model_name='routeauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeauditevent',
            name='route_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='routing.routeplan'),
        ),
        migrations.AddField(
            model_name='routeoptimizationrun',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_optimization_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeoptimizationrun',
            name='route_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='routing.routeplan'),
        ),
        migrations.AddField(
            model_name='routestopline',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stop_lines', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='routestopline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stop_lines', to='products.product'),
        ),
        migrations.AddField(
            model_name='routestopline',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='routing.routestop'),
        ),
        migrations.AddIndex(
            model_name='routeauditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='routing_rou_event_t_0803c4_idx'),
        ),
        migrations.AddIndex(
            model_name='routestopline',
            index=models.Index(fields=['order_item'], name='routing_rou_order_i_aba7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='routestopline',
            index=models.Index(fields=['product'], name='routing_rou_product_5ac4e0_idx'),
        ),
    ]
