# Generated by Django 5.2.6 on 2026-04-15 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerces', '0001_initial'),
        ('distributors', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('PREPARING', 'Preparando'), ('ON_THE_WAY', 'En camino'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commerce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commerces.commerce')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='distributors.distributor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
