# Generated by Django 5.2.6 on 2026-04-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerces', '0003_initial'),
        ('distributors', '0002_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['distributor', 'created_at'], name='orders_orde_distrib_8195ff_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['distributor', 'status'], name='orders_orde_distrib_7e3d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['commerce', 'created_at'], name='orders_orde_commerc_8c1559_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
    ]
