# Generated by Django 5.2.6 on 2026-04-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerces', '0003_initial'),
        ('distributors', '0002_initial'),
        ('orders', '0002_order_orders_orde_distrib_8195ff_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['distributor', 'branch'], name='orders_orde_distrib_52f93b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['distributor', 'seller'], name='orders_orde_distrib_37ebca_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['distributor', 'channel'], name='orders_orde_distrib_a75043_idx'),
        ),
    ]
