# Generated by Django 5.2.6 on 2026-04-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_branch_order_channel_order_seller_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_distrib_52f93b_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_distrib_37ebca_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_distrib_a75043_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
