# Generated by Django 5.2.6 on 2026-04-22 00:07

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_orders_orde_distrib_52f93b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_window_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_date',
            field=models.DateField(default=apps.orders.models.default_dispatch_date),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='volume_m3',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('PREPARING', 'Preparando'), ('SCHEDULED', 'Programado'), ('ON_THE_WAY', 'En camino'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
