# Generated by Django 5.2.6 on 2026-04-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('mercado_pago_link', models.URLField(blank=True)),
                ('max_products', models.PositiveIntegerField(default=500)),
                ('max_drivers', models.PositiveIntegerField(default=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Prueba'), ('ACTIVE', 'Activa'), ('PAST_DUE', 'Vencida'), ('SUSPENDED', 'Suspendida')], default='TRIAL', max_length=20)),
                ('mercado_pago_link', models.URLField(blank=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['distributor__business_name'],
            },
        ),
    ]
