# Generated by Django 5.2.6 on 2026-04-15 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='distributor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='distributors.distributor'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan'),
        ),
    ]
