# Generated by Django 5.2.6 on 2026-04-21 01:26

from urllib.parse import parse_qs, urlparse
from django.db import migrations, models


def seed_preapproval_plan_ids(apps, schema_editor):
    Plan = apps.get_model('billing', 'Plan')
    for plan in Plan.objects.all():
        if plan.mp_preapproval_plan_id or not plan.mp_subscription_url:
            continue
        query = parse_qs(urlparse(plan.mp_subscription_url).query)
        preapproval_plan_id = (query.get('preapproval_plan_id') or [''])[0]
        if preapproval_plan_id:
            plan.mp_preapproval_plan_id = preapproval_plan_id
            plan.save(update_fields=['mp_preapproval_plan_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_dynamic_marketing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='mp_preapproval_plan_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='mercado_pago_subscription_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.RunPython(seed_preapproval_plan_ids, migrations.RunPython.noop),
    ]
