# Generated by Django 5.2.6 on 2026-04-15 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=60)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('IN_ROUTE', 'En ruta'), ('MAINTENANCE', 'Mantenimiento'), ('INACTIVE', 'Inactivo')], default='AVAILABLE', max_length=20)),
                ('insurance_expires_at', models.DateField(blank=True, null=True)),
                ('inspection_expires_at', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=80)),
                ('license_category', models.CharField(max_length=40)),
                ('license_expires_at', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=40)),
                ('emergency_contact', models.CharField(blank=True, max_length=180)),
                ('available', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='distributors.distributor')),
            ],
            options={
                'ordering': ['user__full_name'],
            },
        ),
    ]
