# Generated by Django 5.2.6 on 2026-04-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
