# Generated by Django 5.2.6 on 2026-04-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=180)),
                ('legal_name', models.CharField(blank=True, max_length=180)),
                ('tax_id', models.CharField(blank=True, max_length=40)),
                ('contact_name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trade_name'],
            },
        ),
    ]
