# Generated by Django 5.2.6 on 2026-04-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerces', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='default_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commerce',
            name='default_window_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
