# Generated by Django 5.2.6 on 2026-04-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=180)),
                ('tax_id', models.CharField(max_length=40, unique=True)),
                ('contact_name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('plan_name', models.CharField(default='Mayorista', max_length=80)),
                ('subscription_status', models.CharField(choices=[('TRIAL', 'Prueba'), ('ACTIVE', 'Activa'), ('PAST_DUE', 'Vencida'), ('SUSPENDED', 'Suspendida')], default='TRIAL', max_length=20)),
                ('mercado_pago_link', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
    ]
