# Generated by Django 5.2.6 on 2026-04-21 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_mp_preapproval_plan_id_and_more'),
        ('distributors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='DistributorOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=180)),
                ('tax_id', models.CharField(max_length=40, unique=True)),
                ('contact_name', models.CharField(max_length=180)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('ACCOUNT_CREATED', 'Cuenta creada'), ('PLAN_SELECTED', 'Plan seleccionado'), ('CHECKOUT_PENDING', 'Checkout pendiente'), ('ACTIVE', 'Activa'), ('REVIEW_REQUIRED', 'Revisar manualmente'), ('FAILED', 'Fallida')], default='ACCOUNT_CREATED', max_length=32)),
                ('mercado_pago_subscription_id', models.CharField(blank=True, max_length=120)),
                ('mercado_pago_status', models.CharField(blank=True, max_length=60)),
                ('review_reason', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('checkout_started_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributor_onboardings', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
