# Generated by Django 5.2.6 on 2026-04-15 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('unit', models.CharField(default='unidad', max_length=40)),
                ('package_size', models.CharField(blank=True, max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image_url', models.URLField(blank=True)),
                ('stock_minimum', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='distributors.distributor')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('distributor', 'sku')},
            },
        ),
    ]
