# Generated by Django 5.2.6 on 2026-04-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['distributor', 'category'], name='products_pr_distrib_9fe85f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['distributor', 'active'], name='products_pr_distrib_ab03ea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
    ]
