# Generated by Django 5.2.6 on 2026-04-16 00:13

import django.db.models.deletion
from django.db import migrations, models


def seed_categories_from_products(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductCategory = apps.get_model("products", "ProductCategory")
    for product in Product.objects.exclude(category="").select_related("distributor"):
        category, _ = ProductCategory.objects.get_or_create(
            distributor=product.distributor,
            name=product.category,
        )
        product.product_category = category
        product.save(update_fields=["product_category"])


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_initial'),
        ('products', '0002_product_cost_product_products_pr_distrib_9fe85f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimension_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('m', 'm'), ('mm', 'mm')], default='cm', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='packages_per_pallet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_package',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_pallet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g')], default='kg', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='distributors.distributor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.productcategory')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategories', to='distributors.distributor')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productsubcategory'),
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='distributors.distributor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productsupplier'),
        ),
        migrations.RunPython(seed_categories_from_products, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['distributor', 'subcategory'], name='products_pr_distrib_7400a7_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['distributor', 'active'], name='products_pr_distrib_93cfa6_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['distributor', 'name'], name='products_pr_distrib_7536ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('distributor', 'name')},
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['distributor', 'active'], name='products_pr_distrib_4679e1_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategory',
            index=models.Index(fields=['category', 'name'], name='products_pr_categor_c33415_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsubcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['distributor', 'active'], name='products_pr_distrib_a21018_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['distributor', 'name'], name='products_pr_distrib_5cd17a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsupplier',
            unique_together={('distributor', 'name')},
        ),
    ]
