# Generated by Django 5.2.6 on 2026-04-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('products', 'Productos'), ('customers', 'Clientes'), ('vehicles', 'Vehículos'), ('drivers', 'Choferes'), ('stock', 'Stock')], max_length=40)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
